### PR TITLE
Added EOL

### PR DESCRIPTION
**Pull request by fhamon**
Yeah, it's my last PR for the t-shirt.

### CODE REVIEW

**Comment by fhamon** [comment]
This PR is a waste of time

**Comment by fhamon** [comment]
I mean, it's juste an EOL

**Comment by fhamon** [comment]
And I don't even use sublime text

**Comment by fhamon** [comment]
Anyway, I have my free t-shirt now

**Comment by fhamon** [comment]
Good day to you sir.

**Comment by dominic-blain** [comment]
Nicely done!

**Pull request merged**
